module.exports = {
    SECTION_CHANGE:"SECTION_CHANGE",
    FILE_SEND:"FILE_SEND",
    SOCKET_READY:"SOCKET_READY",
    STREAMING_DATA:"STREAMING_DATA",
    UPLOAD_START:"UPLOAD_START",
    UPLOAD_COMPLETE:"UPLOAD_COMPLETE",
    SEND_META:"SEND_META",
    GET_CONTENT:"GET_CONTENT",
    LOAD_CONTENT_REQUEST:"LOAD_CONTENT_REQUEST",
    LOAD_CONTENT_SUCCESS:"LOAD_CONTENT_SUCCESS",
    LOAD_CONTENT_FAIL:"LOAD_CONTENT_FAIL"
};