module.exports = {
    SECTION_CHANGE:"SECTION_CHANGE",
    FILE_SEND:"FILE_SEND",
    SOCKET_READY:"SOCKET_READY",
    STREAMING_DATA:"STREAMING_DATA",
    UPLOAD_START:"UPLOAD_START",
    UPLOAD_COMPLETE:"UPLOAD_COMPLETE"
};