module.exports = {
    SECTION_CHANGE:"SECTION_CHANGE",
    FILE_SEND:"FILE_SEND",
    SOCKET_READY:"SOCKET_READY",
    STREAMING_DATA:"STREAMING_DATA",
    UPLOAD_START:"UPLOAD_START",
    UPLOAD_COMPLETE:"UPLOAD_COMPLETE",
    SEND_META:"SEND_META",
    GET_CONTENT:"GET_CONTENT",
    RECEIVE_CONTENT_RESULTS:"RECEIVE_CONTENT_RESULTS",
    CHANGE_CONTENT_SECTION:"CHANGE_CONTENT_SECTION",
    CHANGE_CURRENT_PAGE:"CHANGE_CURRENT_PAGE",
    SORT_CONTENT:"SORT_CONTENT",
    FILTER_CONTENT:"FILTER_CONTENT",
    SET_FILTER:"SET_FILTER"
};